# Backend
FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY packages/backend/package*.json ./
RUN npm install

COPY packages/backend/src ./src
COPY packages/backend/prisma ./prisma
COPY packages/backend/tsconfig.json ./

RUN npm run build

EXPOSE 3000

# Run migrations and then start the app
CMD ["sh", "-c", "npm run prisma:push && npm start"]
